name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t vex-custom-game-web-app/vex-custom-game-calculator .
      - name: Publish Image to Docker Hub
        run: docker push vex-custom-game-web-app/vex-custom-game-calculator:latest

  deploy: 
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull vex-custom-game-web-app/vex-custom-game-calculator:latest
      - name: Delete Old Container
        run: docker rm -f vex-custom-game-calculator-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name vex-custom-game-calculator-container vex-custom-game-web-app/vex-custom-game-calculator"