name: CICD

on:
  push:
    branch: deploy-to-ec2
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name:
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with: 'temurin'
        java-version: '17'
      - name: Build Project
        run: mvn clean instal -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p $ {{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t Vex\ Custom\ Game\ Web\ App/vex-custom-game-calculator .
      - name: Publish image to docker hub
        run: docker push Vex\ Custom\ Game\ Web\ App/vex-custom-game-calculator:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull Vex\ Custom\ Game\ Web\ App/vex-custom-game-calculator:latest
      - name: Delete old container
        run: docker rm -f vex-custom-game-calculator-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name vex-custom-game-calculator-container Vex\ Custom\ Game\ Web\ App/vex-custom-game-calculator
	  
		